name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened' || (github.event.action == 'labeled' && github.event.label.name == 'product')
      with:
        project: 'https://github.com/cbrock/my-boxen/projects/1'
        column_name: 'Needs triage'
